from Tkinter import *
import sqlite3
from datetime import datetime
from tabulate import tabulate
date_format = "%d/%m/%Y"
con=sqlite3.Connection("mydb")
cur=con.cursor()
root=Tk()
root["bg"]="sky blue"
root.title("Loan Manager")
Label(root,text="NAME",relief=RIDGE,width=20,bg="light green",fg="blue").grid(row=0,column=0)
Label(root,text="ID",relief=RIDGE,width=20,bg="light green",fg="blue").grid(row=1,column=0)
Label(root,text="LOAN NO.",relief=RIDGE,width=20,bg="light green",fg="blue").grid(row=2,column=0)
Label(root,text="START DATE",relief=RIDGE,width=20,bg="light green",fg="blue").grid(row=3,column=0)
Label(root,text="END DATE",relief=RIDGE,width=20,bg="light green",fg="blue").grid(row=4,column=0)
Label(root,text="AMOUNT TAKEN",relief=RIDGE,width=20,bg="light green",fg="blue").grid(row=5,column=0)
Label(root,text="AMOUNT RETURNED",relief=RIDGE,width=20,bg="light green",fg="blue").grid(row=6,column=0)
Label(root,text="RATE OF INTEREST",relief=RIDGE,width=20,bg="light green",fg="blue").grid(row=7,column=0)
Label(root,text="NO INTEREST DAYS",relief=RIDGE,width=20,bg="light green",fg="blue").grid(row=8,column=0)
Label(root,text="TOTAL SI",relief=RIDGE,width=20,bg="light green",fg="blue").grid(row=9,column=0)
n=Entry(root,relief=SUNKEN,width=30,bg="light yellow")
n.grid(row=0,column=2)
idd=Entry(root,relief=SUNKEN,width=30,bg="light yellow")
idd.grid(row=1,column=2)
l=Entry(root,relief=SUNKEN,width=30,bg="light yellow")
l.grid(row=2,column=2)
strt_date=Entry(root,relief=SUNKEN,width=30,bg="light yellow")
strt_date.grid(row=3,column=2)
end_date=Entry(root,relief=SUNKEN,width=30,bg="light yellow")
end_date.grid(row=4,column=2)
p=Entry(root,relief=SUNKEN,width=30,bg="light yellow")
p.grid(row=5,column=2)
artrn=Entry(root,relief=SUNKEN,width=30,bg="light yellow")
artrn.grid(row=6,column=2)
r=Entry(root,relief=SUNKEN,width=30,bg="light yellow")
r.grid(row=7,column=2)
intrst=Entry(root,relief=SUNKEN,width=30,bg="light yellow")
intrst.grid(row=8,column=2)
def insert():
    a=()
    a=(n.get(),idd.get(),l.get(),datetime.strptime(strt_date.get(),date_format),datetime.strptime(end_date.get(),date_format),p.get(),artrn.get(),r.get(),intrst.get())
    cur.execute("insert into records(name,id,lno,sdate,edate,pr,ramt,rate,no_intrst) values(?,?,?,?,?,?,?,?,?)",a)
    con.commit()
def delete():
    cur.execute("delete from records where lno=?",l.get())
    con.commit()
def calcu():
        a=datetime.strptime(end_date.get(),date_format).date()
        b=datetime.strptime(strt_date.get(),date_format).date()
        delta=(a-b).days
        delta=delta-int(intrst.get())
        si2=float(artrn.get())*float(r.get())*float(delta)/(36500)
        u=(si2,idd.get())
        cur.execute("insert into records(si) values(?) where id=?",u)
def clear():
    n.delete(0,'end')
    idd.delete(0,'end')
    l.delete(0,'end')
    strt_date.delete(0,'end')
    end_date.delete(0,'end')
    p.delete(0,'end')
    artrn.delete(0,'end')
    r.delete(0,'end')
    intrst.delete(0,'end')
def search():
    if len(idd.get())==0:
        root=Tk()
        root["bg"]="sky blue"
        root.title("Search Result")
        d=tabulate({"ID":(cur.execute("select distinct id from records"))},headers="keys")
        Label(root,text=d,bg="sky blue").grid(row=12,column=0)
        c=tabulate({"NAMES":(cur.execute("select distinct name from records"))},headers="keys")
        Label(root,text=c,bg="sky blue").grid(row=12,column=1)
    if len(idd.get())!=0 and len(l.get())==0:
        root=Tk()
        root["bg"]="sky blue"
        root.title("Search Result")
        c=tabulate({"NAMES":(cur.execute("select distinct name from records where id=?",idd.get()))},headers="keys")
        Label(root,text=c,bg="sky blue").grid(row=12,column=0)
        d=tabulate({"LOAN NO":(cur.execute("select lno from records where id=?",idd.get()))},headers="keys")
        Label(root,text=d,bg="sky blue").grid(row=12,column=1)
        f=tabulate({"PRINCIPAL":(cur.execute("select pr from records where id=?",idd.get()))},headers="keys")
        Label(root,text=f,bg="sky blue").grid(row=12,column=2)
    if len(idd.get())!=0 and len(l.get())!=0:
        t=(idd.get(),l.get())
        cur.execute('select name from records where id=? and lno=?',t)
        c=cur.fetchall()
        n.insert(0,c)
        cur.execute('select sdate from records where id=? and lno=?',t)
        c=cur.fetchall()
        strt_date.insert(0,c)
        cur.execute('select edate from records where id=? and lno=?',t)
        c=cur.fetchall()
        end_date.insert(0,c)
        cur.execute('select pr from records where id=? and lno=?',t)
        c=cur.fetchall()
        p.insert(0,c)
        cur.execute('select ramt from records where id=? and lno=?',t)
        c=cur.fetchall()
        artrn.insert(0,c)
Button(root,text="INSERT",height=1,width=10,bg="pink",command=insert).grid(row=10,column=0,padx=20,pady=10)
Button(root,text="DELETE",height=1,width=10,bg="pink",command=delete).grid(row=10,column=1,padx=20,pady=10)
Button(root,text="SEARCH",height=1,width=10,bg="pink",command=search).grid(row=10,column=2,padx=20,pady=10)
Button(root,text="CALCULATE",height=1,width=10,bg="pink",command=calcu).grid(row=10,column=3,padx=20,pady=10)
Button(root,text="CLEAR",height=1,width=10,bg="pink",command=clear).grid(row=11,column=1,padx=20,pady=10)
Button(root,text="EXIT",height=1,width=10,bg="pink",command=root.destroy).grid(row=11,column=2,padx=20,pady=10)

con.commit()
root.mainloop()
